# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vectorize.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vectorize.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fvectorize.proto\x12\rimportservice\"R\n\x10VectorizeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0e\n\x06region\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\"3\n\x11VectorizeResponse\x12\x11\n\tembedding\x18\x01 \x03(\x02\x12\x0b\n\x03\x64im\x18\x02 \x01(\x05\x32m\n\x10VectorizeService\x12Y\n\x12GetEmbeddingVector\x12\x1f.importservice.VectorizeRequest\x1a .importservice.VectorizeResponse\"\x00\x42<\n(com.example.importservice.grpc.vectorizeB\x0eVectorizeProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vectorize_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n(com.example.importservice.grpc.vectorizeB\016VectorizeProtoP\001'
  _globals['_VECTORIZEREQUEST']._serialized_start=34
  _globals['_VECTORIZEREQUEST']._serialized_end=116
  _globals['_VECTORIZERESPONSE']._serialized_start=118
  _globals['_VECTORIZERESPONSE']._serialized_end=169
  _globals['_VECTORIZESERVICE']._serialized_start=171
  _globals['_VECTORIZESERVICE']._serialized_end=280
# @@protoc_insertion_point(module_scope)
