<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.example</groupId>
        <artifactId>import-service</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>model</artifactId>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-json</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.pgvector</groupId>
            <artifactId>pgvector</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.jsonschema2pojo</groupId>
                <artifactId>jsonschema2pojo-maven-plugin</artifactId>
                <version>1.2.1</version>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/main/resources/schema</sourceDirectory>
                    <targetPackage>com.github.sanandroid.importservice.model.wine</targetPackage>
                    <includeAdditionalProperties>false</includeAdditionalProperties>
                    <annotationStyle>jackson2</annotationStyle>
                    <useTitleAsClassname>false</useTitleAsClassname>
                    <includeJsr303Annotations>true</includeJsr303Annotations>
                    <useJakartaValidation>true</useJakartaValidation>
                    <includeGetters>true</includeGetters>
                    <includeSetters>true</includeSetters>
                    <includeToString>true</includeToString>
                    <includeHashcodeAndEquals>true</includeHashcodeAndEquals>
                    <removeOldOutput>true</removeOldOutput>
                    <sourceType>jsonschema</sourceType>
                    <generateBuilders>true</generateBuilders>
                    <serializable>true</serializable>
                </configuration>
                <executions>
                    <execution>
                        <id>generate-wine-dto</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <sourcePaths>
                                <sourcePath>${project.basedir}/src/main/resources/schema/wine_dto.json</sourcePath>
                            </sourcePaths>
                            <targetPackage>com.github.sanandroid.importservice.model.wine</targetPackage>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-vdp-winery-dto</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <sourcePaths>
                                <sourcePath>${project.basedir}/src/main/resources/schema/vdp_winery_dto.json</sourcePath>
                            </sourcePaths>
                            <targetPackage>com.github.sanandroid.importservice.model.winery</targetPackage>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>