spring.application.name=vector-service
server.port=8080
server.shutdown=graceful

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq

app.rabbitmq.vdp-wineries-queue=wineries.vdp
app.rabbitmq.wines-queue=wines
app.rabbitmq.wineries-exchange=wineries_message
app.rabbitmq.wineries-outbound-queue=wineries_message
app.rabbitmq.wineries-routing-key=wineries_message

 spring.datasource.url=jdbc:postgresql://localhost:5432/vector_db
spring.datasource.username=vector_user
spring.datasource.password=vector_pass
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


vectorizer.grpc.host=localhost
vectorizer.grpc.port=50051
vectorizer.grpc.plaintext=true

logging.level.org.springframework=INFO
logging.level.com.example.importservice=DEBUG

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized

spring.profiles.active=dev